### ISSUE TITLE
Compatibility with Strapi@3.6

### ISSUE THREAD

**Issue by shah21** [danestves/strapi-plugin-colorpicker#4]
Here is the error that i occured

`Unexpected token r in JSON at position 0
SyntaxError: Unexpected token r in JSON at position 0
    at JSON.parse (<anonymous>)
    at S (http://localhost:1337/admin/main.835f252f.chunk.js:1:6481181)
    at Ka (http://localhost:1337/admin/main.835f252f.chunk.js:1:4286018)
    at Ii (http://localhost:1337/admin/main.835f252f.chunk.js:1:4294922)
    at gl (http://localhost:1337/admin/main.835f252f.chunk.js:1:4333660)
    at cs (http://localhost:1337/admin/main.835f252f.chunk.js:1:4324957)
    at ls (http://localhost:1337/admin/main.835f252f.chunk.js:1:4324882)
    at Xl (http://localhost:1337/admin/main.835f252f.chunk.js:1:4321891)
    at http://localhost:1337/admin/main.835f252f.chunk.js:1:4273276
    at t.unstable_runWithPriority (http://localhost:1337/admin/main.835f252f.chunk.js:1:4348856)`

**Comment by danestves** [comment]
What version of Strapi?

**Comment by shah21** [comment]
> What version of Strapi?

3.6.1

**Comment by danestves** [comment]
I currently doesn't support 3.6 yet, this weekend going to test it and see if there is any new change and update the plugin to the latest version 🙌 stay tunned

**Comment by shah21** [comment]
> I currently doesn't support 3.6 yet, this weekend going to test it and see if there is any new change and update the plugin to the latest version 🙌 stay tunned

ok I am waiting for your new release  🙌

**Comment by danestves** [comment]
Hey @shah21 the past weekend I was full of work but I promise you that this week I’m going to work to put support for the latest Strapi version!

**Comment by raees-digitalsalt** [comment]
Hi Danes,

Did you managed to update the plugin, It is still not working with strapi 3.6

**Comment by danestves** [comment]
Hi @raees-digitalsalt until now there is no support for Strapi 3.6, we don't go to make any future updates to the package until Strapi v4 it's launched
